# spring.application.name=galileo_backend
spring.application.name=GalileoBackendApplicatoin

spring.datasource.url=jdbc:postgresql://localhost:5432/GalileoDB
spring.datasource.username=postgres
spring.datasource.password=sesame

#Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect